### ISSUE TITLE
Project broken/wont start or some other issue

### ISSUE THREAD

**Issue by alexgomes09** [TeamNavdeep/LetsBrawl#37]
**Project wont start. For some reason it causes unity to crash and throws Access Violation error. 
Note that my other unity project and unity itself runs fine. But  making error only when I run this project (Scenes>test.unity). I just pulled recent commit.  Anyone on the same boat ?**

Unity Editor [version: Unity 4.5.5f1_7684ad0c5a44]

Unity.exe caused an Access Violation (0xc0000005)
  in module Unity.exe at 0023:0071b817.

Error occurred at 2015-02-08_181614.
D:\Unity\Editor\Unity.exe, run by Alex.
31% memory in use.
0 MB physical memory [0 MB free].
0 MB paging file [0 MB free].
0 MB user address space [3561 MB free].
Read from location 0000002c caused an access violation.

Context:
EDI:    0x0ae3a644  ESI: 0x0ae2893c  EAX:   0x00000000
EBX:    0x00000000  ECX: 0x00000000  EDX:   0x0ae286dc
EIP:    0x0071b817  EBP: 0x0028e7a0  SegCs: 0x00000023
EFlags: 0x00210246  ESP: 0x0028e798  SegSs: 0x0000002b

Bytes at CS:EIP:
8b 4b 2c 56 f6 c1 01 74 0b 8d 4b 2c e8 08 81 d0 
.............Stack: .. .... ...

**Comment by SirLouisSmith** [comment]
I just tried running the project from GitHub and it seems to be working fine to me. The error only happened with the most current version of the project?

**Comment by alexgomes09** [comment]
yes error happened with the current version of the project. First I tried pulling and merging with old version I had, then problem occurred. Then I deleted entire project and cloned down project twice. Same error. Unfortunately error log doesn't really specify enough. Doing some research on what might have caused this problem :(

**Comment by an1k3t** [comment]
If Unity is crashing as soon as you load the scene, I'm guessing there must some conflict of internal files. Try copying the project to another location and then run it from there, also rename the scene to something else

**Comment by an1k3t** [comment]
This could also be related to the issue that Justin and Nav told me about, where something goes wrong with the files in a Unity project when you work with GitHub, so maybe copy the project over and then delete the scene and try to recreate it, if the above doesn't work

**Comment by NavdeepHayer** [comment]
Unity and github doesn't work together very well make sure that all the object have there script and everything I can make a working build this week just make sure everyone has all of there most up to date scripts on git

**Comment by an1k3t** [comment]
Ok so I checked on your issue Alex, and it seems its something different for everyone, but the theme seems to be that some important system file becomes bugged/corrupt, so it seems you might have to re-install Unity

**Comment by alexgomes09** [comment]
Thnxs Aniket and others. Could not figure out what was the main problem but gave up figuring out and re-installing latest version of unity seems to fixed the problem. Project loading fine. :)
